version: '3.7'

services:
  db:
    build:
      dockerfile: Dockerfile
      target: dev
      context: ./database
    image: ${APP_NAME}-db
    container_name: ${APP_NAME}-db
    volumes:
      #- ./database/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./database/data/:/data/db
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGO_INITDB_DATABASE
      - MONGO_HOSTNAME=$MONGO_HOSTNAME
      - MONGO_PORT=$MONGO_PORT
      - MONGO_USER=$MONGO_USER
      - MONGO_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27018:${MONGO_PORT}"
      - "9222:9222"
    networks:
      - app-network
    #entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
  server:
    build:
      target: dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "9229:9229"
    env_file: .env
    command: npm run start-dev
    environment:
      - NODE_ENV=development
      - PORT=$SERVER_PORT
    depends_on:
      - db
  client:
    build:
      dockerfile: Dockerfile
      target: dev
    environment:
      - NODE_ENV=development  
    depends_on:
      - server
networks:
    app-network:
        driver: bridge
volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local